#!/usr/bin/env python3

dane = []

with open('Dane/szachy.txt','r') as f:
	p = []
	for i in f:
		if i.strip() == '':
			dane.append(p)	
			p = []
			continue
		p.append(i.strip())

for i in dane:
	z = eval('a for a in i')
	for y in zip(z):
		print(y)
		print()
